apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private5g
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/bharathyadavgd2004/Private5g.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: open5gs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
