apiVersion: v1
kind: ConfigMap
metadata:
  name: gnb-config
  namespace: open5gs
data:
  gnb.yaml: |
    mcc: '999'
    mnc: '70'
    nci: '0x000000010'
    idLength: 32
    tac: 1
    linkIp: POD_IP
    ngapIp: POD_IP
    gtpIp: POD_IP
    ignoreStreamIds: true
    amfConfigs:
      - address: open5gs-amf
        port: 38412
    slices:
      - sst: 1
